### ISSUE TITLE
Exposing the server argument for rain

### ISSUE THREAD

**Issue by didnt1able** [likjou/TBitTorrent#2]
Is it possible to run rain server as a daemon while still allowing access to the tui.

Allowing for having the server command be put in an init script to run on boot while allowing for something like `tbitorrent console' to access the tui.

I'm not sure how feasible this is but it would be really neat for headless installs.

**Comment by likjou** [comment]
its probably doable i think, i like the idea of that too but i created this just for my Final year project soooo this might be the final version. 

however, according to this post, there might be another library that can do exactly what you wanted.
Here is the link:
[https://stackoverflow.com/questions/62569234/can-i-run-a-golang-application-as-a-background-process-without-nohup](url)
