### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by ghost** [likjou/TBitTorrent#3]
could you provide a release

**Comment by likjou** [comment]
done but only for win amd 64. you can compile yourself with go build . and i fixed some import issue.

**Comment by ghost** [comment]
it seems to work nicely. the torrent I added started downloading in an instant, despite not having that many seeders. the UI is also extremely pleasant to look at, and displays more information than some established clients out there such as transmission. there are some more things to implement before it reaches usability though. firstly, I'd implement a settings panel, so that you could, among other things, set download location, port, network interface, speed limits, DHT, max connections, and so on. you can get inspiration from utorrent, qbittorrent, picotorrent and transmission for the settings. I think being able to set download location in general and per-torrent is the most essential feature to implement at the moment. This would also make it possible for TBit to recognize already-existent torrents - coupled with a torrent recheck function, of course. 

furthermore, there should be a way to paste stuff. maybe some sort of clipboard detection? having to type all magnet links and torrent paths isn't particularly convenient.

speaking of convenience, considering it is a command line application, perhaps it would be better to have it running as a system service, so that you wouldn't need to have the cmd window opened at all times. you can open a hidden cmd window with VBScript and a bat, but then I'm not sure if you would be able to open it from another cmd to interact with it. in any case, the idea is to have it either on system tray, or as a service.

considering this is the first release, it's already much better than the vast majority of clients out here. great work

**Comment by ghost** [comment]
btw, you should warn people not to let their cmd windows get too small, otherwise the program will crash.

**Comment by likjou** [comment]
Wow thanks for all the recommendation. But i am too busy with work and lost motivation to continue to develop this :( . So this might be the last version of it. However, if you are interested you could help to improve this. Who knows maybe someday in the future i might come back to this. i will close this for now. Thanks for having interest in my project :)

**Comment by ghost** [comment]
> Wow thanks for all the recommendation. But i am too busy with work and lost motivation to continue to develop this :( . So this might be the last version of it. However, if you are interested you could help to improve this. Who knows maybe someday in the future i might come back to this. i will close this for now. Thanks for having interest in my project :)

It's alright. I have 0 experience with Go and to be honest it's not a language I'm interested in, so I hope you come back to it, or someone else experienced in the language can implement at least some of the stuff I mentioned. that said, before you go, please add information regarding your project, such as build instructions and whatnot, in a little manual, so that whoever decides to work on this in the future can do so without much difficulty.

**Comment by likjou** [comment]
oh ya also you should be able to right click to paste the entire magnet link into the add magnet link panel i have tried it.
